# 问题
## Error response from daemon: Get "https://index.docker.io/v1/search?q=portainer&n=25": dial tcp: lookup index.docker.io on 172.17.18.18:53: read udp 172.20.220.12:53735->172.17.18.18:53: i/o timeout

网络链接问题